{% set name = "sassc" %}
{% set version = "2.3.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 6f0e15b0aab4b76ef29404b1d27b07850bd66c0d690eab05376cc389d6b6eee3

build:
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
    - make -C {{ PREFIX }}/lib/ruby/gems/{{ ruby }}.0/gems/{{ name }}-{{ version }}/ext clean
  skip: {{ win }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - ruby
  run:
    - ruby
    - rb-ffi >=1.9,<2

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE.txt
  summary: Use libsass with Ruby!

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/sass/sassc-ruby

extra:
  recipe-maintainers:
    - sodre
