travis:
  secure:
    BINSTAR_TOKEN: JqmPmmm+qJvQCM3uCCi9XZHJ9C0pC7k7mbYNFBzd39RKVBs0Wvw7tV1/+QlcD4R1Nc98j9saeDuG/yXxcJE4OeZCzE2nSRAskvaxEnOWDgaCOGuMHgWIjCSZ8sPL6+Ug0+CHQzbeK4g6p/vJgJ1j6e87jOJgPEKfExuO5P9GIqybuU+6PFTxswh/mftfKcX8HLQg9xRQZaIe89dNotdgJPqCvN1g4UlFLRLTzrojv19Uqp5fWL8igi8ofBxCU+jLpGUKZJubXv3VMXa3AhdEd4+xCB9ZjrJj54F3Wc6nU8JcgJwibRYsET8udDTR3M8Zz1mGxfaxc/JMRLI98VV16pIU65we7NtAuRVJBYlUWRotjySqSVUb5BsOPEVybczzWxMwquqK2HgzPSHXOal7kISYFuRLcqcagEttYGlNQ97vivdhvWk/cWW65ZRxqkLeB61te95Huo52jpFRJJ9UCv+AeC+F95SOTM2plCaC1v1Z/g9UPCBxll5xocsBx6PtrSVyt7NcY3BKp3hRwq4gLcuCsDiB1Iyk0Zc/mT1oYdo6L/SSA08TSG+m74JqXdh0x0/DulkmEiJqu2KZ/3eKONnR8S82EPRZRPIGUFbup/pgwqNfqBM7IwpKBI9hilqdUJO0BighKKUZhd6opX5NbJCJkXtNEHg0gJLqFJ83SzI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
